# Generated by Django 3.1.3 on 2020-11-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modumat_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('full_question', models.CharField(max_length=200)),
            ],
        ),
    ]
