# Generated by Django 3.1.3 on 2020-11-09 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modumat_app', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(-1, 'negative'), (0, 'neutral'), (1, 'positive')])),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modumat_app.module')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modumat_app.question')),
            ],
        ),
    ]
